// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZFMuS55p3du3RapHWT6j8S8Ej5qgILk',
    appId: '1:514912023011:web:2f4b6a8c66480aed02f0d6',
    messagingSenderId: '514912023011',
    projectId: 'u-go-c28e1',
    authDomain: 'u-go-c28e1.firebaseapp.com',
    storageBucket: 'u-go-c28e1.firebasestorage.app',
    measurementId: 'G-CFJRJ8MDHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbqhpp0MNrTwGHsH9SBi--ls0kkwtPq8A',
    appId: '1:514912023011:android:a955c8058a02d58f02f0d6',
    messagingSenderId: '514912023011',
    projectId: 'u-go-c28e1',
    storageBucket: 'u-go-c28e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl859svX25V5txkWnjE0_CEX1ctHP0x5A',
    appId: '1:514912023011:ios:82e283e2205dfdf002f0d6',
    messagingSenderId: '514912023011',
    projectId: 'u-go-c28e1',
    storageBucket: 'u-go-c28e1.firebasestorage.app',
    iosBundleId: 'com.example.uGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl859svX25V5txkWnjE0_CEX1ctHP0x5A',
    appId: '1:514912023011:ios:82e283e2205dfdf002f0d6',
    messagingSenderId: '514912023011',
    projectId: 'u-go-c28e1',
    storageBucket: 'u-go-c28e1.firebasestorage.app',
    iosBundleId: 'com.example.uGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZFMuS55p3du3RapHWT6j8S8Ej5qgILk',
    appId: '1:514912023011:web:09b32dfa9c48d94802f0d6',
    messagingSenderId: '514912023011',
    projectId: 'u-go-c28e1',
    authDomain: 'u-go-c28e1.firebaseapp.com',
    storageBucket: 'u-go-c28e1.firebasestorage.app',
    measurementId: 'G-LQE15GN5C9',
  );

}